# Generated by Django 4.0.2 on 2022-03-16 16:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField(default='', max_length=500)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='medium', max_length=6)),
                ('rating', models.CharField(choices=[('1', '1 (Solved optimally as fast as I can type)'), ('2', '2 (Solved in <30 min with few bugs)'), ('3', '3 (Solved in 1 hr with some bugs)'), ('4', "4 (Couldn't solve myself, but understood solution)"), ('5', "5 (If interviewer asks this, I'm doomed)")], default='3', max_length=2, verbose_name='Self Difficulty Rating')),
                ('categories', models.TextField(blank=True, default='', verbose_name='Category Tags (comma separated)')),
                ('companies', models.TextField(blank=True, default='', verbose_name='Company Tags (comma separated)')),
                ('notes', models.TextField(blank=True, default='')),
                ('last_solved', models.DateField(default=datetime.date.today)),
                ('next_solve', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
