# Generated by Django 4.0 on 2022-03-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('difficulty', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('categories', models.JSONField()),
                ('companies', models.JSONField()),
                ('notes', models.TextField()),
                ('last_solved', models.DateField()),
                ('next_solve', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
