# Generated by Django 4.0.2 on 2022-03-17 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='last_solved',
            field=models.DateField(default=datetime.date(2022, 3, 16)),
        ),
    ]
