# Generated by Django 4.0 on 2022-03-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='last_solved',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='next_solve',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='url',
        ),
    ]
