# Generated by Django 4.0 on 2022-03-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_problem_categories_remove_problem_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=6),
        ),
        migrations.AddField(
            model_name='problem',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
