# Generated by Django 4.0 on 2022-03-06 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_problem_url_problem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
