# Generated by Django 4.0 on 2022-03-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_problem_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
