# Generated by Django 4.0 on 2022-03-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_problem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='companies',
            field=models.JSONField(default=dict),
        ),
    ]
