# Generated by Django 4.0 on 2022-03-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_problem_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='companies',
            field=models.TextField(default='', verbose_name='Company Tags (comma separated)'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='rating',
            field=models.CharField(choices=[('1', '1 (Easiest)'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 (Hardest)')], default='3', max_length=2, verbose_name='Self Difficulty Rating'),
        ),
    ]
