# Generated by Django 4.0 on 2022-03-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_problem_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='link',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='rating',
        ),
    ]
