# Generated by Django 4.0 on 2022-03-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_problem_companies_remove_problem_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='link',
            field=models.URLField(default='', max_length=500),
        ),
    ]
