# Generated by Django 4.0 on 2022-03-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_problem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='companies',
            field=models.TextField(blank=True, default='', verbose_name='Company Tags (comma separated)'),
        ),
    ]
