# Generated by Django 4.0 on 2022-03-06 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_problem_categories_problem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='last_solved',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
