# Generated by Django 4.0 on 2022-03-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_problem_last_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='next_solve',
            field=models.DateField(blank=True, null=True),
        ),
    ]
